version: '3.4'

services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'EST5EDT'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /home/hdd1tb_1:/mnt:z
      - /home/hdd1tb_2:/mnt2:z
    command: '-s "hdd1tb_1;/mnt" -s "hdd1tb_2;/mnt2;yes;no;no;bearnas" -u "bearnas;bearpasswd" -p'

networks:
  default: