version: '3.4'

services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'EST5EDT'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
        #read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./smb.conf:/etc/samba/smb.conf
      - /media/hdd1tb_1:/mnt/hdd1tb_1:z
      - /media/hdd2tb_1:/mnt/hdd2tb_1:z
      - /media/hdd5tb_1:/mnt/hdd5tb_1:z
      - /media/hdd6tb_1:/mnt/hdd6tb_1:z
      - /media/hdd6tb_2:/mnt/hdd6tb_2:z
      - /media/hdd2tb_toshiba:/mnt/hdd2tb_toshiba:z   
        #command: '-s "hdd1tb_1;/mnt" -s "hdd2tb_1;/mnt2;yes;no;no;bearnas" -u "bearnas;aelita" -p'
    command: '-u "bearnas;aelita" -p'

networks:
  default:
